title: "Karl Belanger's Portfolio"
description: "Linux Administration Projects, Accessibility Insights, and Homelab Engineering"
remote_theme: "mmistakes/minimal-mistakes@4.28.0"

head_scripts:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - /assets/js/mermaid-init.js

# Build settings
markdown: kramdown
highlighter: rouge

# Minimal Mistakes settings
plugins:
  - jekyll-include-cache

# Navigation
include:
  - index.md
  - projects/projects.md
  - projects/usb_drive_recovery.md
  - projects/home-lab.md
  - projects/nextcloud-aio-project.md
  - my-linux-accessibility-journey.md

# Author info
author:
  name: "Karl Belanger"
  linkedin: "https://www.linkedin.com/in/karl-belanger-09761b21/"

# Defaults for all Markdown pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      toc: true
      toc_label: "On this page"
      toc_icon: "list"
